using System.Collections.Generic;

namespace CosmicRumble.Localization
{
    /// <summary>
    /// Başarım (50) ve görev (14) verilerinin çeviri tablosu — LocStrings.cs ile aynı biçim
    /// (anahtar = İngilizce kaynak metin, dizi sırası [tr, zh, es, ja, ko, de]), ayrı dosyada
    /// tutulur çünkü kaynağı farklı (AchievementDefinition/QuestDefinition .asset alanları,
    /// UI kod satırları değil). Loc.T bu tabloyu LocStrings.Table ile birlikte arar.
    /// </summary>
    public static class LocContentStrings
    {
        public static readonly Dictionary<string, string[]> Table = new Dictionary<string, string[]>
        {
            // ── Achievements ─────────────────────────────────────────────────
            ["Number One"] = new[] { "Bir Numara", "第一名", "Número Uno", "ナンバーワン", "넘버원", "Nummer Eins" },
            ["Reach the top of the leaderboard"] = new[] { "Liderlik tablosunun zirvesine ulaş", "登上排行榜榜首", "Alcanza la cima de la clasificación", "リーダーボードの首位に立つ", "리더보드 1위를 달성하세요", "Erreiche die Spitze der Rangliste" },
            ["Bomb Demolition"] = new[] { "Bomba İmhası", "炸弹拆除", "Demolición con Bomba", "爆弾解体", "폭탄 파괴", "Bombenabriss" },
            ["Destroy a planet's surface with a bomb"] = new[] { "Bir bombayla bir gezegenin yüzeyini yok et", "用炸弹摧毁一个星球的表面", "Destruye la superficie de un planeta con una bomba", "爆弾で惑星の表面を破壊する", "폭탄으로 행성 표면을 파괴하세요", "Zerstöre die Oberfläche eines Planeten mit einer Bombe" },
            ["Hammer Time"] = new[] { "Çekiç Zamanı", "锤子时间", "Hora del Martillo", "ハンマータイム", "해머 타임", "Hammerzeit" },
            ["Knock an enemy off the planet with Bat Hammer"] = new[] { "Bat Hammer ile bir düşmanı gezegenden fırlat", "用蝙蝠锤把敌人击出星球", "Expulsa a un enemigo del planeta con el Bate Martillo", "バットハンマーで敵を惑星から吹き飛ばす", "배트 해머로 적을 행성 밖으로 날려버리세요", "Schlage einen Gegner mit dem Schlägerhammer vom Planeten" },
            ["Cosmic Master"] = new[] { "Kozmik Usta", "宇宙大师", "Maestro Cósmico", "コズミックマスター", "코스믹 마스터", "Kosmischer Meister" },
            ["Win 100 matches"] = new[] { "100 maç kazan", "赢得100场对战", "Gana 100 partidas", "100試合に勝利する", "100경기 승리", "Gewinne 100 Matches" },
            ["Damage Dealer"] = new[] { "Hasar Verici", "伤害输出者", "Causante de Daño", "ダメージディーラー", "데미지 딜러", "Schadensverursacher" },
            ["Deal 1,000 total damage"] = new[] { "Toplam 1.000 hasar ver", "累计造成1,000点伤害", "Inflige 1.000 de daño total", "合計1,000のダメージを与える", "총 1,000 데미지를 입히세요", "Verursache insgesamt 1.000 Schaden" },
            ["Atom Bomb"] = new[] { "Atom Bombası", "原子弹", "Bomba Atómica", "原子爆弾", "원자 폭탄", "Atombombe" },
            ["Deal 250,000 total damage"] = new[] { "Toplam 250.000 hasar ver", "累计造成250,000点伤害", "Inflige 250.000 de daño total", "合計250,000のダメージを与える", "총 250,000 데미지를 입히세요", "Verursache insgesamt 250.000 Schaden" },
            ["Wrecking Machine"] = new[] { "Yıkım Makinesi", "破坏机器", "Máquina Destructora", "破壊マシン", "파괴 머신", "Zerstörungsmaschine" },
            ["Deal 50,000 total damage"] = new[] { "Toplam 50.000 hasar ver", "累计造成50,000点伤害", "Inflige 50.000 de daño total", "合計50,000のダメージを与える", "총 50,000 데미지를 입히세요", "Verursache insgesamt 50.000 Schaden" },
            ["Untouchable"] = new[] { "Dokunulmaz", "无法触及", "Intocable", "アンタッチャブル", "언터처블", "Unberührbar" },
            ["Block 500 damage with Shield"] = new[] { "Kalkan ile 500 hasar engelle", "用护盾格挡500点伤害", "Bloquea 500 de daño con el Escudo", "シールドで500ダメージをブロックする", "실드로 500 데미지를 막으세요", "Blockiere 500 Schaden mit dem Schild" },
            ["Duel Champion"] = new[] { "Düello Şampiyonu", "决斗冠军", "Campeón de Duelo", "デュエルチャンピオン", "결투 챔피언", "Duell-Champion" },
            ["Get 10 wins in 1v1 mode"] = new[] { "1v1 modunda 10 galibiyet al", "在1v1模式中获得10场胜利", "Consigue 10 victorias en el modo 1v1", "1v1モードで10勝する", "1대1 모드에서 10승을 달성하세요", "Erziele 10 Siege im 1-gegen-1-Modus" },
            ["Legend"] = new[] { "Efsane", "传奇", "Leyenda", "レジェンド", "레전드", "Legende" },
            ["Win 50 matches"] = new[] { "50 maç kazan", "赢得50场对战", "Gana 50 partidas", "50試合に勝利する", "50경기 승리", "Gewinne 50 Matches" },
            ["Grenadier"] = new[] { "Bombacı", "掷弹兵", "Granadero", "擲弾兵", "척탄병", "Grenadier" },
            ["Hit 2+ enemies with a single grenade"] = new[] { "Tek bir el bombasıyla 2+ düşmana isabet ettir", "用一颗手雷击中2名以上敌人", "Golpea a 2 o más enemigos con una sola granada", "1つの手榴弾で敵2体以上に命中させる", "수류탄 하나로 2명 이상의 적을 명중시키세요", "Treffe 2 oder mehr Gegner mit einer einzigen Granate" },
            ["First Blood"] = new[] { "İlk Kan", "第一滴血", "Primera Sangre", "ファーストブラッド", "퍼스트 블러드", "Erstes Blut" },
            ["Win your first match"] = new[] { "İlk maçını kazan", "赢得你的第一场对战", "Gana tu primera partida", "初めての試合に勝利する", "첫 경기에서 승리하세요", "Gewinne dein erstes Match" },
            ["Flawless"] = new[] { "Kusursuz", "完美无瑕", "Impecable", "フローレス", "완벽한 승리", "Makellos" },
            ["Win a match without taking damage"] = new[] { "Hiç hasar almadan bir maç kazan", "在不受到任何伤害的情况下赢得一场对战", "Gana una partida sin recibir daño", "ダメージを受けずに試合に勝利する", "데미지를 받지 않고 경기에서 승리하세요", "Gewinne ein Match, ohne Schaden zu nehmen" },
            ["Legend of the Galaxy"] = new[] { "Galaksinin Efsanesi", "银河传奇", "Leyenda de la Galaxia", "銀河の伝説", "은하의 전설", "Legende der Galaxie" },
            ["Complete all 49 other achievements"] = new[] { "Diğer 49 başarımın tamamını tamamla", "完成其余全部49个成就", "Completa los otros 49 logros", "他の49個の実績をすべて達成する", "다른 49개의 업적을 모두 달성하세요", "Schließe alle anderen 49 Erfolge ab" },
            ["Galaxy Regular"] = new[] { "Galaksinin Müdavimi", "银河常客", "Habitual de la Galaxia", "銀河の常連", "은하의 단골", "Galaxie-Stammgast" },
            ["Play 100 matches in total"] = new[] { "Toplamda 100 maç oyna", "累计进行100场对战", "Juega 100 partidas en total", "合計100試合プレイする", "총 100경기를 플레이하세요", "Spiele insgesamt 100 Matches" },
            ["Planet Killer"] = new[] { "Gezegen Katili", "星球杀手", "Asesino de Planetas", "惑星キラー", "행성 킬러", "Planetentöter" },
            ["Destroy 10 planets in total"] = new[] { "Toplamda 10 gezegen yok et", "累计摧毁10个星球", "Destruye 10 planetas en total", "合計10個の惑星を破壊する", "총 10개의 행성을 파괴하세요", "Zerstöre insgesamt 10 Planeten" },
            ["Challenge Everyone"] = new[] { "Herkese Meydan Oku", "挑战全场", "Desafía a Todos", "全員に挑戦", "모두에게 도전", "Fordere alle heraus" },
            ["Deal damage to 7 different players in the same match"] = new[] { "Aynı maçta 7 farklı oyuncuya hasar ver", "在同一场对战中对7名不同玩家造成伤害", "Inflige daño a 7 jugadores diferentes en la misma partida", "同じ試合で7人の異なるプレイヤーにダメージを与える", "같은 경기에서 서로 다른 7명의 플레이어에게 데미지를 입히세요", "Verursache in einem Match Schaden bei 7 verschiedenen Spielern" },
            ["Speed Run"] = new[] { "Hız Koşusu", "极速通关", "Carrera Rápida", "スピードラン", "스피드런", "Speedrun" },
            ["Win a match within 5 turns"] = new[] { "5 tur içinde bir maç kazan", "在5回合内赢得一场对战", "Gana una partida en 5 turnos o menos", "5ターン以内に試合に勝利する", "5턴 이내에 경기에서 승리하세요", "Gewinne ein Match innerhalb von 5 Zügen" },
            ["Home Run"] = new[] { "Home Run", "本垒打", "Jonrón", "ホームラン", "홈런", "Homerun" },
            ["Send an enemy hit by Bat Hammer into another enemy"] = new[] { "Bat Hammer ile vurduğun düşmanı başka bir düşmana çarptır", "用蝙蝠锤把敌人击飞并撞向另一名敌人", "Envía a un enemigo golpeado por el Bate Martillo contra otro enemigo", "バットハンマーで敵を吹き飛ばして別の敵にぶつける", "배트 해머로 친 적을 다른 적에게 부딪히게 하세요", "Schleudere einen vom Schlägerhammer getroffenen Gegner in einen anderen Gegner" },
            ["Revenge"] = new[] { "İntikam", "复仇", "Venganza", "リベンジ", "복수", "Rache" },
            ["Defeat whoever killed you in the next match"] = new[] { "Seni öldüren kişiyi bir sonraki maçta yen", "在下一场对战中击败杀死你的人", "Derrota a quien te eliminó en la siguiente partida", "次の試合で自分を倒した相手を倒す", "다음 경기에서 자신을 처치한 상대를 물리치세요", "Besiege in der nächsten Partie denjenigen, der dich getötet hat" },
            ["Precision"] = new[] { "Hassasiyet", "精准", "Precisión", "精密射撃", "정밀함", "Präzision" },
            ["Finish a match with 80% accuracy (min. 10 shots)"] = new[] { "Bir maçı %80 isabet oranıyla bitir (en az 10 atış)", "以80%命中率结束一场对战（至少10次射击）", "Termina una partida con 80% de precisión (mín. 10 disparos)", "命中率80%で試合を終える（最低10発）", "명중률 80%로 경기를 마치세요 (최소 10발)", "Beende ein Match mit 80% Trefferquote (mind. 10 Schüsse)" },
            ["Teleported"] = new[] { "Işınlandı", "已传送", "Teletransportado", "テレポート", "텔레포트", "Teleportiert" },
            ["Teleport behind an enemy and land a hit"] = new[] { "Bir düşmanın arkasına ışınlan ve isabet ettir", "传送到敌人身后并成功命中", "Teletranspórtate detrás de un enemigo y acierta un golpe", "敵の背後にテレポートして攻撃を命中させる", "적의 뒤로 순간이동하여 공격을 명중시키세요", "Teleportiere dich hinter einen Gegner und lande einen Treffer" },
            ["Wall of Shields"] = new[] { "Kalkan Duvarı", "护盾之墙", "Muro de Escudos", "シールドウォール", "방패의 벽", "Schildwall" },
            ["Block 3 attacks with Shield"] = new[] { "Kalkan ile 3 saldırı engelle", "用护盾格挡3次攻击", "Bloquea 3 ataques con el Escudo", "シールドで3回の攻撃をブロックする", "실드로 공격 3회를 막으세요", "Blockiere 3 Angriffe mit dem Schild" },
            ["Black Hole Master"] = new[] { "Kara Delik Ustası", "黑洞大师", "Maestro del Agujero Negro", "ブラックホールマスター", "블랙홀 마스터", "Schwarzes-Loch-Meister" },
            ["Pull in 3 enemies at once with Black Hole"] = new[] { "Kara Delik ile aynı anda 3 düşmanı çek", "用黑洞同时吸入3名敌人", "Atrae a 3 enemigos a la vez con el Agujero Negro", "ブラックホールで一度に敵3体を引き込む", "블랙홀로 동시에 적 3명을 끌어당기세요", "Ziehe mit dem Schwarzen Loch gleichzeitig 3 Gegner heran" },
            ["Sharpshooter"] = new[] { "Keskin Nişancı", "神射手", "Tirador Certero", "シャープシューター", "명사수", "Scharfschütze" },
            ["Land 10 headshots with the pistol"] = new[] { "Tabancayla 10 kafa vuruşu yap", "用手枪打出10次爆头", "Consigue 10 disparos a la cabeza con la pistola", "ピストルで10回のヘッドショットを決める", "권총으로 헤드샷 10회를 성공시키세요", "Erziele 10 Kopftreffer mit der Pistole" },
            ["Cosmic Hunter"] = new[] { "Kozmik Avcı", "宇宙猎人", "Cazador Cósmico", "コズミックハンター", "코스믹 헌터", "Kosmischer Jäger" },
            ["Reach the top 10 on the leaderboard"] = new[] { "Liderlik tablosunda ilk 10'a gir", "进入排行榜前10名", "Alcanza el top 10 de la clasificación", "リーダーボードでトップ10に入る", "리더보드 상위 10위 안에 드세요", "Erreiche die Top 10 der Rangliste" },
            ["Cosmic Crew"] = new[] { "Kozmik Ekip", "宇宙小队", "Tripulación Cósmica", "コズミッククルー", "코스믹 크루", "Kosmische Crew" },
            ["Play 5 matches with the same 3 people"] = new[] { "Aynı 3 kişiyle 5 maç oyna", "与相同的3人进行5场对战", "Juega 5 partidas con las mismas 3 personas", "同じ3人と5試合プレイする", "같은 3명과 5경기를 플레이하세요", "Spiele 5 Matches mit denselben 3 Personen" },
            ["Quantum"] = new[] { "Kuantum", "量子", "Cuántico", "クォンタム", "퀀텀", "Quanten" },
            ["Use Teleport 5 times in a single match"] = new[] { "Tek bir maçta 5 kez Işınlan kullan", "在一场对战中使用5次传送", "Usa Teletransporte 5 veces en una sola partida", "1試合でテレポートを5回使用する", "한 경기에서 텔레포트를 5회 사용하세요", "Nutze Teleport 5-mal in einem einzigen Match" },
            ["Mentor"] = new[] { "Rehber", "导师", "Mentor", "メンター", "멘토", "Mentor" },
            ["Guide a new player through the tutorial"] = new[] { "Yeni bir oyuncuya öğreticide rehberlik et", "引导一名新玩家完成教程", "Guía a un nuevo jugador a través del tutorial", "新しいプレイヤーをチュートリアルで導く", "새로운 플레이어에게 튜토리얼을 안내하세요", "Führe einen neuen Spieler durch das Tutorial" },
            ["Event Horizon"] = new[] { "Olay Ufku", "事件视界", "Horizonte de Sucesos", "事象の地平線", "사건의 지평선", "Ereignishorizont" },
            ["Pull in 50 enemies in total with Black Hole"] = new[] { "Kara Delik ile toplamda 50 düşman çek", "累计用黑洞吸入50名敌人", "Atrae a 50 enemigos en total con el Agujero Negro", "ブラックホールで合計50体の敵を引き込む", "블랙홀로 총 50명의 적을 끌어당기세요", "Ziehe mit dem Schwarzen Loch insgesamt 50 Gegner heran" },
            ["Demolitions Expert"] = new[] { "Yıkım Uzmanı", "爆破专家", "Experto en Demoliciones", "解体エキスパート", "폭파 전문가", "Sprengmeister" },
            ["Fire 100 total shots with the RPG"] = new[] { "RPG ile toplamda 100 atış yap", "累计用火箭筒发射100次", "Dispara 100 veces en total con el RPG", "RPGで合計100発発射する", "RPG로 총 100발을 발사하세요", "Feuere insgesamt 100 Schüsse mit dem RPG ab" },
            ["Pin Puller"] = new[] { "Pim Çekici", "拉环高手", "Sacador de Anillas", "ピンプラー", "핀 뽑기 달인", "Splint-Zieher" },
            ["Fire 25 shots with the grenade"] = new[] { "El bombasıyla 25 atış yap", "用手雷投掷25次", "Lanza 25 granadas", "手榴弾を25回投げる", "수류탄으로 25회 발사하세요", "Wirf 25-mal die Granate" },
            ["Pump Master"] = new[] { "Pompa Ustası", "泵动大师", "Maestro de Bombeo", "ポンプマスター", "펌프 마스터", "Pump-Meister" },
            ["Hit 5 enemies in a row with the shotgun"] = new[] { "Pompalıyla art arda 5 düşmana isabet ettir", "用霰弹枪连续击中5名敌人", "Golpea a 5 enemigos seguidos con la escopeta", "ショットガンで5体連続で敵に命中させる", "샷건으로 연속 5명의 적을 명중시키세요", "Treffe mit der Schrotflinte 5 Gegner in Folge" },
            ["Competitive"] = new[] { "Rekabetçi", "好胜者", "Competitivo", "コンペティティブ", "경쟁심", "Wettbewerbsfähig" },
            ["Finish top 3 in a ranked match"] = new[] { "Dereceli bir maçta ilk 3'e gir", "在排位赛中进入前3名", "Termina en el top 3 en una partida clasificatoria", "ランクマッチでトップ3に入る", "랭크 경기에서 상위 3위 안에 드세요", "Erreiche die Top 3 in einem gewerteten Match" },
            ["Rocketeer"] = new[] { "Roketçi", "火箭兵", "Cohetero", "ロケッティア", "로켓 조종사", "Raketentechniker" },
            ["Deal damage to 3+ enemies with a single RPG shot"] = new[] { "Tek bir RPG atışıyla 3+ düşmana hasar ver", "用一发火箭筒对3名以上敌人造成伤害", "Inflige daño a 3 o más enemigos con un solo disparo de RPG", "1発のRPGで敵3体以上にダメージを与える", "RPG 한 발로 3명 이상의 적에게 데미지를 입히세요", "Verursache mit einem einzigen RPG-Schuss Schaden bei 3 oder mehr Gegnern" },
            ["Buckshot Storm"] = new[] { "Saçma Yağmuru", "霰弹风暴", "Tormenta de Perdigones", "バックショットストーム", "산탄 폭풍", "Schrotkugel-Sturm" },
            ["Land every pellet of a shotgun blast"] = new[] { "Bir pompalı atışının tüm saçmalarını isabet ettir", "让霰弹枪的所有弹丸全部命中", "Acierta con todos los perdigones de un disparo de escopeta", "ショットガンの弾をすべて命中させる", "샷건 발사의 모든 탄환을 명중시키세요", "Treffe mit allen Kugeln eines Schrotflintenschusses" },
            ["Tough Stance"] = new[] { "Sağlam Duruş", "顽强姿态", "Postura Firme", "タフスタンス", "굳건한 자세", "Zähe Haltung" },
            ["Take 10,000 total damage and survive"] = new[] { "Toplamda 10.000 hasar al ve hayatta kal", "累计承受10,000点伤害并存活", "Recibe 10.000 de daño total y sobrevive", "合計10,000のダメージを受けて生き残る", "총 10,000 데미지를 받고 생존하세요", "Erleide insgesamt 10.000 Schaden und überlebe" },
            ["Champions League"] = new[] { "Şampiyonlar Ligi", "冠军联赛", "Liga de Campeones", "チャンピオンズリーグ", "챔피언스 리그", "Champions League" },
            ["Win in an 8-player lobby"] = new[] { "8 oyunculu bir lobide kazan", "在8人房间中获胜", "Gana en una sala de 8 jugadores", "8人ロビーで勝利する", "8인 로비에서 승리하세요", "Gewinne in einer 8-Spieler-Lobby" },
            ["War Machine"] = new[] { "Savaş Makinesi", "战争机器", "Máquina de Guerra", "ウォーマシン", "전쟁 기계", "Kriegsmaschine" },
            ["Win 25 matches"] = new[] { "25 maç kazan", "赢得25场对战", "Gana 25 partidas", "25試合に勝利する", "25경기 승리", "Gewinne 25 Matches" },
            ["Trigger Happy"] = new[] { "Tetikçi", "扣扳机成瘾", "Gatillo Fácil", "トリガーハッピー", "방아쇠광", "Schießwütig" },
            ["Fire 100 shots"] = new[] { "100 atış yap", "发射100次", "Dispara 100 veces", "100発発射する", "100발을 발사하세요", "Feuere 100 Schüsse ab" },
            ["Bullet Factory"] = new[] { "Mermi Fabrikası", "子弹工厂", "Fábrica de Balas", "弾丸工場", "탄환 공장", "Kugelfabrik" },
            ["Fire 1,000 shots"] = new[] { "1.000 atış yap", "发射1,000次", "Dispara 1.000 veces", "1,000発発射する", "1,000발을 발사하세요", "Feuere 1.000 Schüsse ab" },
            ["Last Breath"] = new[] { "Son Nefes", "最后一口气", "Último Aliento", "ラストブレス", "마지막 숨", "Letzter Atemzug" },
            ["Win a match at 1 HP"] = new[] { "1 canla bir maç kazan", "以1点生命值赢得一场对战", "Gana una partida con 1 de vida", "HP1で試合に勝利する", "체력 1로 경기에서 승리하세요", "Gewinne ein Match mit 1 Lebenspunkt" },
            ["Social Butterfly"] = new[] { "Sosyal Kelebek", "社交蝴蝶", "Mariposa Social", "社交的な蝶", "사교적인 나비", "Gesellschaftsschmetterling" },
            ["Play a match with 8 different players"] = new[] { "8 farklı oyuncuyla bir maç oyna", "与8名不同玩家进行一场对战", "Juega una partida con 8 jugadores diferentes", "8人の異なるプレイヤーと試合をする", "서로 다른 8명의 플레이어와 경기하세요", "Spiele ein Match mit 8 verschiedenen Spielern" },
            ["Super Hero"] = new[] { "Süper Kahraman", "超级英雄", "Superhéroe", "スーパーヒーロー", "슈퍼 히어로", "Superheld" },
            ["Land on an enemy with Super Jump to deal damage"] = new[] { "Süper Zıplama ile bir düşmanın üzerine inip hasar ver", "用超级跳跃落在敌人身上造成伤害", "Aterriza sobre un enemigo con Super Salto para infligir daño", "スーパージャンプで敵の上に着地してダメージを与える", "슈퍼 점프로 적 위에 착지하여 데미지를 입히세요", "Lande mit dem Superjump auf einem Gegner, um Schaden zu verursachen" },
            ["Pistoleer"] = new[] { "Tabancacı", "手枪手", "Pistolero", "ピストラー", "권총병", "Pistolero" },
            ["Hit 50 enemies with the pistol"] = new[] { "Tabancayla 50 düşmana isabet ettir", "用手枪击中50名敌人", "Golpea a 50 enemigos con la pistola", "ピストルで敵50体に命中させる", "권총으로 적 50명을 명중시키세요", "Treffe 50 Gegner mit der Pistole" },
            ["Full Arsenal"] = new[] { "Tam Cephanelik", "全副武装", "Arsenal Completo", "フルアーセナル", "완전 무장", "Volles Arsenal" },
            ["Use all 5 weapons in a single match"] = new[] { "Tek bir maçta 5 silahın tamamını kullan", "在一场对战中使用全部5种武器", "Usa las 5 armas en una sola partida", "1試合で5種類の武器すべてを使用する", "한 경기에서 5개의 무기를 모두 사용하세요", "Benutze alle 5 Waffen in einem einzigen Match" },
            ["Gunslinger"] = new[] { "Silahşor", "枪手", "Pistolero Rápido", "ガンスリンガー", "총잡이", "Revolverheld" },
            ["Fire 30 shots in a single match"] = new[] { "Tek bir maçta 30 atış yap", "在一场对战中发射30次", "Dispara 30 veces en una sola partida", "1試合で30発発射する", "한 경기에서 30발을 발사하세요", "Feuere 30 Schüsse in einem einzigen Match ab" },
            ["Underdog"] = new[] { "Zayıf Taraf", "逆袭者", "Desvalido", "アンダードッグ", "언더독", "Außenseiter" },
            ["Win while every enemy has more HP than you"] = new[] { "Tüm düşmanların senden fazla canı varken kazan", "在所有敌人生命值都比你高时获胜", "Gana mientras todos los enemigos tienen más vida que tú", "全ての敵が自分よりHPが高い状態で勝利する", "모든 적이 자신보다 체력이 많을 때 승리하세요", "Gewinne, während jeder Gegner mehr HP hat als du" },
            ["Veteran"] = new[] { "Emektar", "老兵", "Veterano", "ベテラン", "베테랑", "Veteran" },
            ["Win 10 matches"] = new[] { "10 maç kazan", "赢得10场对战", "Gana 10 partidas", "10試合に勝利する", "10경기 승리", "Gewinne 10 Matches" },
            ["Orbit"] = new[] { "Yörünge", "轨道", "Órbita", "オービット", "궤도", "Umlaufbahn" },
            ["Change planets with Super Jump and take a shot"] = new[] { "Süper Zıplama ile gezegen değiştir ve atış yap", "使用超级跳跃切换星球并进行射击", "Cambia de planeta con Super Salto y realiza un disparo", "スーパージャンプで惑星を移動して攻撃する", "슈퍼 점프로 행성을 이동한 후 공격하세요", "Wechsle mit dem Superjump den Planeten und gib einen Schuss ab" },

            // ── Quests ───────────────────────────────────────────────────────
            ["Skilled"] = new[] { "Yetenekli", "熟练", "Hábil", "スキルド", "숙련됨", "Geschickt" },
            ["Use any ability today"] = new[] { "Bugün herhangi bir yetenek kullan", "今日使用任意技能", "Usa cualquier habilidad hoy", "今日いずれかのアビリティを使用する", "오늘 아무 스킬이나 사용하세요", "Setze heute eine beliebige Fähigkeit ein" },
            ["Black Hole Power"] = new[] { "Kara Delik Gücü", "黑洞之力", "Poder del Agujero Negro", "ブラックホールの力", "블랙홀의 힘", "Schwarzes-Loch-Kraft" },
            ["Use Black Hole today"] = new[] { "Bugün Kara Delik kullan", "今日使用黑洞", "Usa el Agujero Negro hoy", "今日ブラックホールを使用する", "오늘 블랙홀을 사용하세요", "Setze heute das Schwarze Loch ein" },
            ["Deal Damage"] = new[] { "Hasar Ver", "造成伤害", "Inflige Daño", "ダメージを与える", "데미지 주기", "Schaden verursachen" },
            ["Land 1 headshot today"] = new[] { "Bugün 1 kafa vuruşu yap", "今日打出1次爆头", "Consigue 1 disparo a la cabeza hoy", "今日ヘッドショットを1回決める", "오늘 헤드샷 1회를 성공시키세요", "Erziele heute einen Kopftreffer" },
            ["Planet Hunter"] = new[] { "Gezegen Avcısı", "星球猎人", "Cazador de Planetas", "惑星ハンター", "행성 사냥꾼", "Planetenjäger" },
            ["Destroy 1 planet today"] = new[] { "Bugün 1 gezegen yok et", "今日摧毁1个星球", "Destruye 1 planeta hoy", "今日惑星を1個破壊する", "오늘 행성 1개를 파괴하세요", "Zerstöre heute einen Planeten" },
            ["Playtime"] = new[] { "Oyun Zamanı", "游戏时间", "Tiempo de Juego", "プレイタイム", "플레이 타임", "Spielzeit" },
            ["Play 2 matches today"] = new[] { "Bugün 2 maç oyna", "今日进行2场对战", "Juega 2 partidas hoy", "今日2試合プレイする", "오늘 2경기를 플레이하세요", "Spiele heute 2 Matches" },
            ["Shooting Practice"] = new[] { "Atış Antrenmanı", "射击练习", "Práctica de Tiro", "射撃練習", "사격 연습", "Schießübung" },
            ["Win Today"] = new[] { "Bugün Kazan", "今日获胜", "Gana Hoy", "今日勝利する", "오늘 승리하기", "Heute gewinnen" },
            ["Lord of Destruction"] = new[] { "Yıkım Lordu", "毁灭领主", "Señor de la Destrucción", "破壊の王", "파괴의 군주", "Herr der Zerstörung" },
            ["Deal 50,000 damage this month"] = new[] { "Bu ay 50.000 hasar ver", "本月造成50,000点伤害", "Inflige 50.000 de daño este mes", "今月50,000のダメージを与える", "이번 달 50,000 데미지를 입히세요", "Verursache diesen Monat 50.000 Schaden" },
            ["Monthly Warrior"] = new[] { "Aylık Savaşçı", "月度战士", "Guerrero Mensual", "マンスリーウォリアー", "월간 전사", "Monatlicher Krieger" },
            ["Play 50 matches this month"] = new[] { "Bu ay 50 maç oyna", "本月进行50场对战", "Juega 50 partidas este mes", "今月50試合プレイする", "이번 달 50경기를 플레이하세요", "Spiele diesen Monat 50 Matches" },
            ["Ability Collection"] = new[] { "Yetenek Koleksiyonu", "技能收集", "Colección de Habilidades", "アビリティコレクション", "스킬 컬렉션", "Fähigkeitensammlung" },
            ["Use 3 different abilities this week"] = new[] { "Bu hafta 3 farklı yetenek kullan", "本周使用3种不同技能", "Usa 3 habilidades diferentes esta semana", "今週3種類の異なるアビリティを使用する", "이번 주 서로 다른 스킬 3개를 사용하세요", "Setze diese Woche 3 verschiedene Fähigkeiten ein" },
            ["Destroyer"] = new[] { "Yok Edici", "毁灭者", "Destructor", "デストロイヤー", "파괴자", "Zerstörer" },
            ["Deal 5,000 damage this week"] = new[] { "Bu hafta 5.000 hasar ver", "本周造成5,000点伤害", "Inflige 5.000 de daño esta semana", "今週5,000のダメージを与える", "이번 주 5,000 데미지를 입히세요", "Verursache diese Woche 5.000 Schaden" },
            ["Weapon Master"] = new[] { "Silah Ustası", "武器大师", "Maestro de Armas", "武器マスター", "무기 마스터", "Waffenmeister" },
            ["Use every weapon this week"] = new[] { "Bu hafta tüm silahları kullan", "本周使用所有武器", "Usa todas las armas esta semana", "今週すべての武器を使用する", "이번 주 모든 무기를 사용하세요", "Benutze diese Woche jede Waffe" },
            ["Weekly Champion"] = new[] { "Haftanın Şampiyonu", "本周冠军", "Campeón Semanal", "ウィークリーチャンピオン", "주간 챔피언", "Wochenchampion" },
            ["Win 10 matches this week"] = new[] { "Bu hafta 10 maç kazan", "本周赢得10场对战", "Gana 10 partidas esta semana", "今週10試合に勝利する", "이번 주 10경기를 승리하세요", "Gewinne diese Woche 10 Matches" },
        };
    }
}
